# Generated by Django 5.1.7 on 2025-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_sig', '0002_course_customuser_enrolled_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, related_name='completed_users', to='log_sig.course'),
        ),
    ]
